### ISSUE TITLE
Share buttons not working

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/desktop#10]
As Flash is not installed. This probably needs to be fixed on the Gitter server side to not include Copy buttons if the app is the Desktop app as I think shipping Flash as part of the app is about as cool as the fiery depths of hell on a very hot day.

**Comment by waltfy** [comment]
Can we get a print screen of this issue? We don't seem to be able to reproduce it locally.

![screen shot 2015-01-28 at 15 30 06](https://cloud.githubusercontent.com/assets/1257595/5940428/ad04781e-a702-11e4-9800-bec5297e0bdc.png)

**Comment by waltfy** [comment]
We have now set the `plugins` to `false`.

https://github.com/nwjs/nw.js/wiki/Manifest-format#plugin
