### ISSUE TITLE
Tray icon missing on Ubuntu (no way to restore window)

### ISSUE THREAD

**Issue by awishformore** [gitterHQ/desktop#101]
On elementary os (which is based on Ubuntu 14.04), there is no tray icon in the notification tray. Was able to reproduce on Ubuntu original and other versions of Ubuntu as well.

This is problematic because once you close the user interface using the cross, there is really no way to reopen the client, even though it is still running in the background.

Other applications work fine like this because relaunching the application will simply activate the current instance if it is already running. Gitter, on the other hand, tries to launch a new instance, which fails because of an already held lock on sqlite.

Even if it would launch fine, it would be undesirable to have many instances running in parrallel. An easy (but less clean) fix would thus be to simply make a launch of the application activate the already running instance if one exists.

I think the issue is related to the fact that elementary os freya is built on Ubuntu 14.04 LTS, but uses a different window manager or tray manager (it uses Wingpanel for the tray afaik). I was able to solve a similar issue with dropbox using the following workaround:

https://unix.stackexchange.com/questions/198977/dropbox-tray-icon-doesnt-show-up-in-elementary-os-luna-freya

It suggests that on elementary os, applications should use libappindicator and the unity desktop environment to have a working tray icon.

**Comment by MadLittleMods** [comment]
I can confirm that there doesn't seem to be a way to restore after closing the active chat window.

**Comment by MadLittleMods** [comment]
Probably blocked until https://github.com/nwjs/nw.js/issues/261

**Comment by MadLittleMods** [comment]
Just tested on Ubuntu 14.04.03 with the [latest release](https://github.com/gitterHQ/desktop/pull/100) we are working on and it has a tray icon :grinning: - Stay tuned for the release

![](https://i.imgur.com/3kzMrHW.png)

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/desktop/issues/79 ?

**Comment by KhaledElAnsari** [comment]
It's working fine on Ubuntu 14.04LTS but it's not on ElementaryOS! I even get notification after closing the window and I can't reopen it
