### ISSUE TITLE
Loading circle never ends when going from organization channel to org page

### ISSUE THREAD

**Issue by WardBenjamin** [gitterHQ/desktop#102]
In the desktop client, you can click the globe in the top right to go to the organization page from the org. channel. This seems to load as normal, but the loading circle animation never exits after the page has loaded, unlike the Gitter Next web client.

**Comment by WardBenjamin** [comment]
This actually seems to affect all versions of the desktop client, Gitter Next or not.

**Comment by WardBenjamin** [comment]
Even more interestingly, if you're on an org page and you switch from default to Next, the loading circle goes away. Same deal if you are in Next mode, and switch to default.

**Comment by MadLittleMods** [comment]
This has already been address in the recent work on the desktop app which will be released soon: https://github.com/gitterHQ/desktop/pull/100#issue-131554885

This was a problem with the `node-webkit` version we were using and have since updated to `nw.js@v0.12.3`

**Comment by WardBenjamin** [comment]
Thanks!
