### ISSUE TITLE
Citing/quoting does not work correctly in Linux desktop client

### ISSUE THREAD

**Issue by awishformore** [gitterHQ/desktop#104]
When using ALT+click to cite/quote a previous message timestamp in the Linux desktop client, I get the following text instead:

![quote1](https://cloud.githubusercontent.com/assets/3630494/12886120/7ce0b1a2-ce6b-11e5-948e-10e7c165a038.png)

Which results in a message without any content:

![quote2](https://cloud.githubusercontent.com/assets/3630494/12886122/80317c06-ce6b-11e5-8126-339bb3f1c427.png)

**Comment by MadLittleMods** [comment]
@awishformore This is as expected. To actually quote a message with the text content, use the "Quote" option in the drop down(3 dot icon) menu:

![](http://i.imgur.com/dpMiOyb.png)
