### ISSUE TITLE
Option to set (auto)start as minimized

### ISSUE THREAD

**Issue by mfonville** [gitterHQ/desktop#107]
Would it be possible to add an option to start the app minimized?
In the UI it would be nice as an extra toggle when enabling autostart.

Also a general remark; when looking whether this option didn't already exist I expected to be able to see the current parameters with --help, which is non-existent. It might be nice to add that and e.g. -v (for version) for commandline-users.

**Comment by kripod** [comment]
This would be a much needed improvement :+1:

**Comment by nicolas33** [comment]
I'm becoming angry by this software not able to start minimized. Hence, I not starting it anymore. No notifications anymore. The channels defeats the purpose of online instant chat.

**Comment by MadLittleMods** [comment]
@nicolas33 PR welcome

Probably just need to add an if statement around https://github.com/gitterHQ/desktop/blob/7fdeb83ab08567305ce5708953d880046d6cc8dd/nwapp/index.js#L281 with some criteria from a user setting which you can add here https://github.com/gitterHQ/desktop/blob/7fdeb83ab08567305ce5708953d880046d6cc8dd/nwapp/utils/settings.js

**Comment by nicolas33** [comment]
Thanks, done.

**Comment by nicolas33** [comment]
Users can test this. Restart gitter once with this version so that the preferences file is updated. Edit the json preferences manually and set the `startHidden` configuration option to `true` (`~/.config/Gitter/gitter_preferences.json` here). Restart again.

**Comment by nicolas33** [comment]
Menu entry added.

**Comment by ManuelSchneid3r** [comment]
@nicolas33 setting startHidden configuration option to true does not work for me with gitter 3.0.3

**Comment by ManuelSchneid3r** [comment]
Ah damn missed the point that this is a PR :smile:

**Comment by MadLittleMods** [comment]
This has merged into `master` via https://github.com/gitterHQ/desktop/pull/160 courtesy of @nicolas33 and will be in the next release.

**Comment by MadLittleMods** [comment]
This has been released in v3.1.0, https://github.com/gitterHQ/desktop/blob/master/CHANGELOG.md#310---2016-8-16
