### ISSUE TITLE
Multiple Gitter instances at startup on Windows

### ISSUE THREAD

**Issue by bbenoist** [gitterHQ/desktop#114]
Gitter starts twice on my Windows machine. I suspect this to come from the 3.X update but not 100% sure as I do not reboot everyday.

Screenshot of the Windows startup entries.

![image](https://cloud.githubusercontent.com/assets/2091902/13320921/65f18642-dbcc-11e5-8e88-0ec3bb627e93.png)

**Comment by MadLittleMods** [comment]
@bbenoist Thanks for the report!

Another report here: https://gitter.im/gitterHQ/gitter?at=56cf0c3d5233db8e3c05858d

The [update from `2.4.0` to `3.0.0`](https://github.com/gitterHQ/desktop/blob/master/CHANGELOG.md#300---2016-2-23) changed the way we handle startup and moved it from the installer itself to the desktop UI where you can toggle wherever.

I will be adding a patch to reconcile the two entries and only have the new one.

**Comment by MadLittleMods** [comment]
@a11smiles pointed out that `2.4.0` placed a shortcut at `C:\Users\xxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` -> `Gitter` shortcut

And although we don't place it there, this is another spot to look:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp

In `3.0.1`, we add it to the registry: `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` -> `Gitter`

**Comment by bbenoist** [comment]
> @a11smiles pointed out that  2.4.0  placed a shortcut at  `C:\Users\xxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup  ->  Gitter`  shortcut

I have it too. Let's delete this obsolete shortcut!

*pro-tip: refer to `%APPDATA%` instead of `C:\Users\xxx\AppData\Roaming\`, it simplifies reuse of the path* :wink:

> I will be adding a patch to reconcile the two entries and only have the new one.

:+1: for this. A simple deletion of the `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\` shortcut from the installer seems to be the solution...

**Comment by MadLittleMods** [comment]
@bbenoist My problem with referring to `%APPDATA%` is I never know if it is `Local` or `Roaming`

**Comment by a11smiles** [comment]
Well, it really depends on what your 2.4.0 version installer did… If your installer referenced `%APPDATA%` then it will be the same.  If you installer had the path hard-coded, then you’ll need to check the hard-coded path.

Or better yet:

```
if (inLocal)
   // Delete local

if (inRoaming)
  // Delete roaming

```

Kill both birds at the same time.

**Comment by bbenoist** [comment]
> My problem with referring to  %APPDATA%  is I never know if it is  Local  or  Roaming  because it is a bit too ambiguous.

No problem, my remark was just in case you were unaware of it.

I had the same problem before and what helped me remind that `%APPDATA%` is `Roaming` was that `%LOCALAPPDATA%` points to `Local` ([reference](http://ss64.com/nt/syntax-variables.html)) :wink:

**Comment by bbenoist** [comment]
@a11smiles 

> Well, it really depends on what your 2.4.0 version installer did…

[Corresponding source code: windows/gitter.iss#L49](https://github.com/gitterHQ/desktop/blob/2.4.0/windows/gitter.iss)

What's sad is that the [Inno Setup documentation](http://www.jrsoftware.org/iskb.php?startup) does not tells whether `{userstartup}` is for `Roaming` or `Local`... Which means that we are not even sure that it will point to the same location if the user runs the installer with different privileges than for 2.4.

**Comment by a11smiles** [comment]
ouch.

**Comment by a11smiles** [comment]
Well, the `{commonstartup}` is easy - it's the All Users path.  But, I see what you mean for the `{userstartup}`.  

I guess from my psuedo logic above, why not just have two `if` statements to delete if it finds the Gitter link in either section?

**Comment by MadLittleMods** [comment]
@a11smiles @bbenoist Feel free to take a look at the PR and give any feedback: https://github.com/gitterHQ/desktop/pull/115
