### ISSUE TITLE
Can't paste password for login

### ISSUE THREAD

**Issue by michaelsbradleyjr** [gitterHQ/desktop#116]
I just cloned this repo and fired up the dev version, per the instructions in the README – worked without a hitch, awesome!

However, I found that when going through the GitHub login, I was unable to paste my password into the password field. For those of us who use 1Password or something like it, that's a huge pain.

I'm not sure whether that password input has paste disabled by default or if it was a deliberate decision on the part of Gitter devs. Either way, I would suggest it's not a good setting and paste should be allowed. A couple of years ago, there was a brief period when Apple disabled password-pasting in various iOS contexts (e.g. in the App Store; it wasn't disabled previously), but bloody screams were raised by many who use password managers like 1Password (in that case, the iOS app edition) and were/are not willing to change their security-minded habits of using long unmemorable passwords. Apple "caved" in a point release and password-pasting was re-enabled.

**Comment by MadLittleMods** [comment]
@michaelsbradleyjr This is definitely not a decision we made at Gitter. That login is on GitHub itself. I can paste into the password field just fine on OSX with Gitter v3.0.1

**Comment by michaelsbradleyjr** [comment]
Interesting, I'm not sure what made the difference for me.

OS X 10.11.3, node v5.7.0, master branch of gitterHQ/desktop.

Also, I just did a sign out and now I can paste in that field upon subsequent login; but I definitely couldn't on the first round, even after closing and restarting it (i.e. from the command line).

If I ever encounter the behavior again, I'll follow up here; but feel free to close this issue.

**Comment by michaelsbradleyjr** [comment]
Actually, I should have experimented further before my previous comment.

Here is the observed behavior, confirmed multiple times.

Being signed out, because it's the first launch or sign out was done before closing the app, when launching the app (dev version, from the command line), I am unable to paste my password for the GitHub login. If I enter the password manually, then sign out, and start the login process again, without closing the app, I can paste my password.

**Comment by MadLittleMods** [comment]
:+1: I can reproduce only on startup if you aren't already authenticated but only on OSX. Tested on Windows but there aren't any issues.

This must be some weird focus keyboard event issue (maybe with nw.js itself?)

**Comment by MadLittleMods** [comment]
Looks like we just need to add the "Edit" menu bar item to the top bar:

 - https://github.com/nwjs/nw.js/issues/1955
 - https://github.com/nwjs/nw.js/issues/2039

**Comment by MadLittleMods** [comment]
Just needed to add the "Edit" menubar item to the login window, using [`createMacBuiltin('Gitter', {hideEdit: false})`](https://github.com/nwjs/nw.js/wiki/Menu#menucreatemacbuiltinappname). I pushed a fix and it will be in the next release. But you can just pull the changes as it seems you are using the repo.

**Comment by michaelsbradleyjr** [comment]
Works great, thanks!
