### ISSUE TITLE
App not opening on windows 10

### ISSUE THREAD

**Issue by noosxe** [gitterHQ/desktop#118]
Just downloaded and installed the app, nothing happens when trying to run it.

**Comment by 0Huie0** [comment]
Same issue here.

Upon running it a greyed out icon opens momentarily and then disappears.

Also see 5 instances of gitter.exe open one after another and then close.

**Comment by MadLittleMods** [comment]
Thank you for the report, @noosxe abd @0Huie0! This was introduced in the latest `v3.0.2` release when addressing #116 and only happened if you weren't already logged in.

I have added a fix and released `v3.0.3`. You will probably need to install manually: https://gitter.im/apps

---

When calling `new gui.Menu(...).createMacBuiltin(...)`
```
Error TypeError: undefined is not a function
    at new LoginView (C:\Users\xxx\AppData\Local\Temp\nw14156_29880\lib\login-view.js:50:10)
    at showAuth (app://gitter/index.js:290:15)
    at initApp (app://gitter/index.js:214:5)
    at app://gitter/index.js:124:3
    at app://gitter/index.js:137:3
```

**Comment by noosxe** [comment]
@MadLittleMods Big thanks! Everything works now.

**Comment by smaccer7** [comment]
Hello @MadLittleMods My laptop came shipped with Windows  Had installed Gitter few months ago and it was all working fine. Had not used gitter for the past few weeks. Launched it earlier today- didn't launch up but gave me an option to update the app, I did and tried but couldn't launch it. Same issue as mentioned by @0Huie0 

I even uninstalled and reinstalled the App, still no go. 

May be the attachment wl help you figure it out.. 

![image](https://cloud.githubusercontent.com/assets/20052332/20032605/ac8f309a-a3b3-11e6-9e13-f64c2d7e78c8.png)

Hope it wl be fixed ASAP...

**Comment by smaccer7** [comment]
@MadLittleMods it looks like it is open but it ain't. Clicking on the icon on task bar doesn't help 👎

**Comment by MadLittleMods** [comment]
@smaccer7 Please create a new separate issue instead of digging up an old one. Feel free to reference the old one though.
