### ISSUE TITLE
Unable to hide conversation

### ISSUE THREAD

**Issue by joshbivens** [gitterHQ/desktop#128]
When you click the "x" next to a user's name on the sidebar to leave the conversation, an option pops up to hide the conversation. Clicking "hide" does nothing.

**Comment by nicolas33** [comment]
Same bug, here.

**Comment by MadLittleMods** [comment]
Please note that this is not a desktop bug. 

I created an issue here that you can track: https://github.com/gitterHQ/gitter/issues/1187
