### ISSUE TITLE
Add black/white menu bar icon option

### ISSUE THREAD

**Issue by vinkla** [gitterHQ/desktop#129]
It would be nice if the menu bar icon could be black/white. Currently it doesn't really blend in since all other icons are black/white/transparent.

<img width="131" alt="screen shot 2016-03-20 at 6 07 54 pm" src="https://cloud.githubusercontent.com/assets/499192/13905671/de3ec40e-eec6-11e5-9212-4a545956fa6c.png">

What do you guys think? We could add it to a settings page maybe?

**Comment by MadLittleMods** [comment]
It could be improved to meet the OSX aesthetic but doesn't standout too much:

![](https://i.imgur.com/WUi3FAb.png)

**Comment by vinkla** [comment]
Closing and cleaning up old issues.
