### ISSUE TITLE
Notifications still appear when "Show Notifications" is disabled

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/desktop#130]
Notifications still appear when "Show Notifications" is disabled.

Probably coming from the iframe inside as they don't have an avatar or sound.

Reproduced on Windows 10

Other reproductions: 

 - https://gitter.im/gitterHQ/gitter?at=56ee7ffd654d30d022e484e8
 - One other in the `gitterHQ/gitter` room but I can't find it

---

I'm leery of this description but is how I experienced it. It seemed to be after disabling "Show notifications" in the desktop app and getting a mention, all messages come through. And restarting the app doesn't fix it. It did respect my setting for a little bit.

**Comment by ochrons** [comment]
This also happens on Ubuntu Linux (and Windows 10). The "Show Notification" has no effect. Client version 3.0.3.

Very annoying.

**Comment by mydigitalself** [comment]
This should have been fixed a little while ago. Let us know if you are still experiencing​ it and reopen the issue.
