### ISSUE TITLE
Private messages are not displayed in the sidebar on desktop

### ISSUE THREAD

**Issue by hyperknot** [gitterHQ/desktop#133]
In the desktop client, OS X 10.9.5, the private message tabs are not visible in the left sidebar.

left Chrome, right desktop client:
<img width="549" alt="screen shot 2016-03-29 at 13 24 55" src="https://cloud.githubusercontent.com/assets/494223/14106513/e177becc-f5b1-11e5-9f33-827dc897d6cb.png">

**Comment by MadLittleMods** [comment]
Can you trying exiting and re-opening the desktop app?

I can see one-to-ones just fine.

**Comment by hyperknot** [comment]
Ok, it seems to have helped.

**Comment by hyperknot** [comment]
Ok, I got a new PM from a new person, and it's still not displayed. I do get the notification in OS X bar, and if I click it, it opens the conversation in the main view, but the sidebar is still not displaying the person.

**Comment by MadLittleMods** [comment]
Inspect element and see if you have any errors in the console. I suspect it just isn't getting the updates and exiting->re-opening will fix the issue.

**Comment by hyperknot** [comment]
There are no errors in console. only the missing .map files from
http://beta-internal:8080/job/gitter-webapp-build-step/4967/artifact/output/maps/router-chat.css.map

**Comment by hyperknot** [comment]
So yes, if I restart the desktop app after every time a new person messages
me, it appears in the left side.
