### ISSUE TITLE
Search bar?

### ISSUE THREAD

**Issue by hedii** [gitterHQ/desktop#134]
Maybe i am stupid, but i cannot find any search bar:
<img width="1830" alt="capture d ecran 2016-03-31 a 09 43 25" src="https://cloud.githubusercontent.com/assets/5358048/14168967/6dc9dd82-f725-11e5-852d-2b4ff9ef25d6.png">
<img width="1830" alt="capture d ecran 2016-03-31 a 09 44 43" src="https://cloud.githubusercontent.com/assets/5358048/14168968/6dcb5e5a-f725-11e5-9a75-6de2ab8ae5a6.png">

**Comment by MadLittleMods** [comment]
Hey @hedii. This isn't desktop app specific so should of been opened on the [`gitterHQ/gitter` repo](https://github.com/gitterHQ/gitter) or even pop into the [chat room](https://gitter.im/gitterHQ/gitter).

The search bar isn't on the explore page anymore and we opted to go for those explicit tags to filter between rooms.


It looks like you are caught in the transition period where it is a bit difficult to get into your first room when going through the home page flow. If you join any room, the search bar in the top-right will search for rooms across all of Gitter. Also, there should be some suggestions in your left-menu but they could have been dismissed

This new user experience has been better addressed with the [new left-menu](http://blog.gitter.im/2016/03/15/introducing-our-new-ui/) with the search always being on the left-menu and a better emphasis on suggestions and communities.
