### ISSUE TITLE
I get double notifications on all of my clients

### ISSUE THREAD

**Issue by PFCKrutonium** [gitterHQ/desktop#135]
I have a client running on Arch Linux (FXDE) and two on Windows, and on all of them when I receive a message on Gitter, I get a notification from the client missing formatting - Escape Characters are visible and there is no name or image on the notification, followed by a message with all of that applied correctly.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/desktop/issues/130. The underlying problem is the same.
