### ISSUE TITLE
Room topic containing url link has weird formatting.

### ISSUE THREAD

**Issue by udiboy1209** [gitterHQ/desktop#136]
I recently switched to the desktop version of gitter. Previously I was using the website.
The topic shows up correctly on the website but on the desktop app(tried latest master and v3.0.3) it shows like this:

![screenshot from 2016-04-11 22 37 53](https://cloud.githubusercontent.com/assets/7384411/14435705/cd90001a-0036-11e6-993d-556b664e2dd8.png)

and this:

![screenshot from 2016-04-11 22 38 52](https://cloud.githubusercontent.com/assets/7384411/14435706/cd9728f4-0036-11e6-9587-dc8b4222f8d0.png)

The actual text of the topic is:

```

People: http://www.giyf.com/. Please don't ask questions like "Is this possible?". Search on google and think of ways you could implement them.
```

**Comment by MadLittleMods** [comment]
@udiboy1209 This is fixed on `next` and you probably just aren't using `next` on the desktop app.

See https://github.com/gitterHQ/gitter/issues/1199
