### ISSUE TITLE
There are no way to search for the room

### ISSUE THREAD

**Issue by Sitin** [gitterHQ/desktop#140]
It is not possible to search for a room from desktop client. The 'home/explore' page looks very poor and shows only predefined set of repos.

I suggest to add a search field just above the rooms list at the left sidebar. It may both filter existing rooms and help to find new one.

**Comment by MadLittleMods** [comment]
@Sitin The search on the top-right when viewing any room will search for rooms across Gitter as well as messages in the current room.

With the [new left-menu](http://blog.gitter.im/2016/03/15/introducing-our-new-ui/), search has moved to the left-menu but has the same functionality.

---

As an aside, if you want to find rooms by tag, you can use explore with this URL trick which is not easily changeable in the desktop client but readily accessible in browser. `https://gitter.im/explore/tags/php`
