### ISSUE TITLE
OS X: Can't paste screen capture image from clipboard

### ISSUE THREAD

**Issue by circa1977** [gitterHQ/desktop#142]
On OS X, if I take a screenshot using Ctrl+Shift+Cmd+4, it doesn't paste into the Gitter window.

This does work in other apps, such as HipChat, browser-based email clients, etc. It also worked for me on Ubuntu.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/1040
