### ISSUE TITLE
BiDi basedirection support

### ISSUE THREAD

**Issue by dov** [gitterHQ/desktop#149]
The desktop client does not correctly calculate the basedirection when entering RTL (right to left) text. Below I will use upper case for RTL characters (as is the convention in UAX#9).

If the user enters the logical sequence (HELO and three (neutral) periods):  H E L O . . .

The expected rendering is:

...OLEH

But the currently shown rendering is:

OLEH...

The reason is that the base direction has not been set to RTL. The determination of the basedirection is typically heuristic based. Here are a couple of popular heuristics:

1. Use the first strong character as the base direction.
2. Calcuate the number of LTR vs RTL in the line and if one is predominant, choose the base direction accordingly.

Such heuristics are used e.g. in the GtkWidget (here I wrote the heuristics for it :-), in Google chat, and in the telegram linux desktop client.

In addition, when the base direction is RTL the contents should be right aligned.

Reference:
* UAX9 - http://unicode.org/reports/tr9/

**Comment by MadLittleMods** [comment]
Open this on the main repo https://github.com/gitterHQ/gitter/issues, this doesn't seem like a desktop specific issue.

**Comment by dov** [comment]
I just tested it on android and it happens there as well. 

Ok, I'll open the issue on the main repo.

Thanks.
