### ISSUE TITLE
Fonts are blurry in Windows client

### ISSUE THREAD

**Issue by zihotki** [gitterHQ/desktop#155]
Please see the attached picture. The back window is FF, the front one is Gitter for windows. I'm using Windows 10.
![capture](https://cloud.githubusercontent.com/assets/114631/17255325/0b6b5312-55b9-11e6-8eff-ab6c2fb513b0.PNG)

**Comment by MadLittleMods** [comment]
Slightly different aliasing but not blurry which is what I would expect from different rendering engines. It looks completely normal to me as a Chrome user. The font aliasing in FF is the one that looks weird to me and is a bit crunchy.

Here is the same setup on my Windows 10 machine.

### Firefox in background

![](http://i.imgur.com/40XlHjX.png)

### Chrome in background

![](http://i.imgur.com/GdtxFa7.png)

**Comment by zihotki** [comment]
Actually you are right, it's an [Chrome issue](https://www.reddit.com/r/firefox/comments/4ubge7/firefox_has_dramatically_better_text_rendering/) so I'm closing this one.
