### ISSUE TITLE
Notifications are sometimes delayed several minutes

### ISSUE THREAD

**Issue by LB--** [gitterHQ/desktop#158]
The toast notifications don't immediately appear anymore, and seem to be delayed. I get notifications for messages I have already read as a result. When I close gitter sometimes a bunch of the notifications come through at once. I've caught multiple toast processes active in my process list while the notifications are in limbo.

However, sometimes the notifications work fine. In either case, the notification _sound_ always plays and the icon always changes color correctly.

This started happening a couple days ago. Coincidentally I actually reformatted my system today and it is still happening on Windows 10 Pro 64-bit 14393.51 with Gitter Desktop v3.0.3, both normal and next.

**Comment by MadLittleMods** [comment]
We use [`node-notifier`](https://www.npmjs.com/package/node-notifier) to show the toast notifications.

You can try running a custom build and logging the time when you receive the event vs the time the notification appears to nail down if it is an issue with the realtime client or the notification library, https://github.com/gitterHQ/desktop/blob/7fdeb83ab08567305ce5708953d880046d6cc8dd/nwapp/index.js#L267

**Comment by LB--** [comment]
In that case, it's probably not an issue with Gitter Desktop then, since the sound and icon are always on time. Sorry for the noise. I'll do some investigation and maybe open an issue over at `node-notifier`.
