### ISSUE TITLE
Gitter loads as a white/blank screen with title node-webkit

### ISSUE THREAD

**Issue by chibieee** [gitterHQ/desktop#159]
![image 1](https://cloud.githubusercontent.com/assets/18466949/17611044/aa39c3d6-6011-11e6-935c-7518ef27a24a.png)

whenever i try to load gitter, it get stuck on this screen.

**Comment by MadLittleMods** [comment]
You can try to enable logging: https://github.com/gitterHQ/desktop#enabling-logging-on-windows

Or even remotely debug the app, `C:\Users\YOUR_USER\AppData\Local\Programs\Gitter --remote-debugging-port=1234` and visit `localhost:1234`

**Comment by chibieee** [comment]
Currently not using a proxy. and i enabled logging via sawbuck. and here is a screenshot of it.
![image2](https://cloud.githubusercontent.com/assets/18466949/17628031/763e60a8-6081-11e6-8132-019bd68ff7e3.png)

**Comment by MadLittleMods** [comment]
@chibieee Can you paste the logs in a [gist](https://gist.github.com/) instead?

It looks like it is failing to load `https://gitter.im/login/oauth/authorize` for some reason :confused: 

 - Has it ever worked for you?
 - Did this only start happening after sign in?
 - What version of windows are you on?

**Comment by chibieee** [comment]
Not entire sure if this is the format you wanted it in, but here are the logs.
https://gist.github.com/chibieee/a6ed1661468a612ad429bb434056bf28

and yes it has worked for me in the past. it recently just stopped working.
it only started happening when i signed out for the first time.
and im currently on windows10 - 64bit. build 10586

**Comment by chibieee** [comment]
It was weird, when i tried connecting to gitter.im, chrome would give me an error and say that the connection was private, and when i would continue anyway, it would redirect me to gettheguy.co.uk

so i did a little debugging and found a solution on the web.
i went into network and sharing center > advanced sharing settings
and turned off network discovery, file and printer sharing, and homegroup connections.

and it worked. i can connect to gitter.im and the gitter desktop app just fine now.
thanks for your help

**Comment by MadLittleMods** [comment]
Weird, do you know what device was mucking things up?

**Comment by chibieee** [comment]
I have no idea, lol
