### ISSUE TITLE
postrm borken in Ubuntu 16.10

### ISSUE THREAD

**Issue by OSryx** [gitterHQ/desktop#162]
I `dpkg` removed _Gitter_ 3.x . Cannot _purge_ config files. 

`postrm` in `dpkg/info` returned errors. need to remove _`/usr/local/bin/gitter` and `/usr/share/applications/gitter.desktop`_ but did not locate them correctly. 

Locate **_gitter_** listed the following config files : 

```
/home/alji/.config/autostart/Gitter.desktop
/home/alji/.config/Gitter/Gitter_config_files*
```

please let me know if you need further informations ...

**Comment by jnv** [comment]
:+1: here. Purging the package ends up with this error:

```
subprocess installed post-removal script returned error exit status 1
```

I have removed [these lines](https://github.com/gitterHQ/desktop/blob/b2c0288f90cc9813648505f9e999ecbaa02657d2/linux/after-remove.sh#L11-L24) from the postrm script and it has uninstalled successfully. You should probably do `rm -f` so the uninstallation does not fail in case the files are not present.
