### ISSUE TITLE
Change font of UI

### ISSUE THREAD

**Issue by manu-silicon** [gitterHQ/desktop#164]
The current font of the Gitter interface does not render very well on Windows when anti-aliasing is disabled.

![image](https://cloud.githubusercontent.com/assets/13194660/18961082/a89d3320-8620-11e6-84f0-8c08db62960f.png)

Below is when I replace the font manually with Arial which renders properly when anti-aliasing is disabled.
![image](https://cloud.githubusercontent.com/assets/13194660/18961214/197167c4-8621-11e6-8fa4-a5ec2ae5bf24.png)

**Comment by MadLittleMods** [comment]
@manu-silicon

 - What browser are you using?
 - What client are you using (webapp, desktop, etc)?
 - What anti-aliasing setting do you have changed?

The fonts look fine in Chrome, Firefox, IE, and Edge on my Windows machine.

**Comment by manu-silicon** [comment]
I'm mostly using Chrome v51 (cannot use anything later than that because they changed font rendering again and it is not usable when anti-aliasing is disabled). I tried Firefox and it renders better (but still not perfectly) but I cannot say if this is because it uses a different font or if it renders it differently.

Both the webapp (Chrome) or desktop behaves the same for me.

In Windows, go to the Advanced system properties and tune the performance by making sure to disable (smooth edges of screen fonts), a restart or logout/login might be required.

Not that on Edge it does render better because it ignores the Windows global setting (like all Windows UWP apps).

**Comment by MadLittleMods** [comment]
I am using Chrome Version 53.0.2785.116 m but the font rendering has been fine for many many many versions.

I'm not sure why you would want to turn off anti-aliasing in Windows and that setting seems to be doing it's job according to those screenshots. Closing as a `wont-fix`.

**Comment by manu-silicon** [comment]
That's a little bit harsh. Do a google search and you will see this is almost an accessibility issue for people like me. The sad thing is that fonts used on website nowadays are not pixel perfect and they render badly as in:
![image](https://cloud.githubusercontent.com/assets/13194660/18963813/464eee74-862b-11e6-9fd8-5f05d04faa69.png)

By 2016 it should be easy to find a font that renders all the time perfectly. They could do it in the 80's and 90's, why not today?

PS: This is not just gitter at fault, it is many websites.

**Comment by MadLittleMods** [comment]
@manu-silicon We use `Source Sans Pro`. If you can find a better hinted version, we would be happy to look at it.

It sounds like you should be using an extension like Stylish to add custom styles for a font you desire though.
