### ISSUE TITLE
Gitter 3.1.0 Login Failing on Windows 7

### ISSUE THREAD

**Issue by jwilczek** [gitterHQ/desktop#168]
When trying to login using Github account on Gitter, I receive the warning:

Hello!
Gitter Windows Desktop App is requesting access to your account.
Do you approve?

When I click "ALLOW", the desktop app is minimized (to the icon tray). When I open it from the icon tray, it shows the exact same warning. I cannot get past this screen.

I've looked at the debug console and there are no errors,. just some mixed content warnings:

"Mixed Content: The page at 'https://gitter.im/login/oauth/authorize?redirect_uri=app%3A%2F%2Fgitter%2Foauth.html&response_type=code&client_id=windows-desktop-prod' was loaded over HTTPS, but requested an insecure resource 'http://beta-internal:8080/job/gitter-webapp-build-step/10117/artifact/output/maps/vendor.js.map'. This content should also be served over HTTPS."

Everytime I click "ALLOW" it launches a new instance of gitter.exe.

And, if I'm watching the console when I click "ALLOW", I see this:

image
![image](https://cloud.githubusercontent.com/assets/8474603/19886655/462c9e60-9ff2-11e6-8002-4e1bb4fe910b.png)

Which, I think, supports my claim that a new instance is being launched each time I click "ALLOW".

(I also verified this is happening by watching Task Manager).

**Comment by jwilczek** [comment]
Is there a resolution to this problem?

**Comment by MadLittleMods** [comment]
Closed in favor of https://github.com/gitterHQ/gitter/issues/1491
