### ISSUE TITLE
: smilie selector should have tabs for complete overview like whatapp etc

### ISSUE THREAD

**Issue by obama** [gitterHQ/desktop#171]
yeah what the title says, i always have to google for a certain smilie, it would be good to browse all

**Comment by MadLittleMods** [comment]
This is a feature request for the whole app and isn't specific to desktop. You should post these sort of things here, https://github.com/gitterHQ/gitter

See 

 - https://github.com/gitterHQ/gitter/issues/1381
 - https://github.com/gitterHQ/gitter/issues/1393
