### ISSUE TITLE
Support pasting images into conversation (in addition to drag-n-drop)

### ISSUE THREAD

**Issue by matthewadams** [gitterHQ/desktop#172]
On Gitter for Mac 1.177.

I used Cmd+Shift+Option+4 to select part of my screen, then tried to paste the copied selection into Gitter desktop client to no avail.  I was forced to save copy as file, then drag-n-drop.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/1040
