### ISSUE TITLE
Can't sign out of Gitter for Mac 10.12

### ISSUE THREAD

**Issue by jldeen** [gitterHQ/desktop#173]
Unable to sign out of Gitter for Mac 10.12. Removed Gitter  and reinstalled. Problem persists.

**Comment by MadLittleMods** [comment]
@jldeen What do you mean "unable to sign out"?

What happens when you press sign out from the menu bar drop down?

![](http://i.imgur.com/XzcQ9IU.png)

**Comment by mydigitalself** [comment]
@jldeen any update?

**Comment by jldeen** [comment]
Sorry about the delay - the holidays. Sign out from menu bar drop down works. I didn't realize that was the way to sign out. This issue is closed.
