### ISSUE TITLE
"Requires High Perf GPU" on MacOS

### ISSUE THREAD

**Issue by tscholak** [gitterHQ/desktop#179]
The Gitter app should not require high performance graphics on MacOS.

**Comment by MadLittleMods** [comment]
I'm not familiar with this requirement. What error are you running into?

You are probably using the  Safari-backed version of the desktop app but you can try the NW.js backed one we have moved to, https://update.gitter.im/osx/Gitter-3.1.0.dmg

**Comment by tscholak** [comment]
I was using version 1.177 of Gitter. For some reason, it was causing the laptop to switch to dedicated graphics. In Activity Monitor, the "Requires High Perf GPU" for Gitter was "Yes".

**Comment by MadLittleMods** [comment]
@tscholak Does Gitter in a browser like Chrome require "Requires High Perf GPU"?

How does the NW.js version of the desktop app perform for you?

**Comment by tscholak** [comment]
The version that you linked to requires the high perf GPU, too. In particular, nwjs Helper does. When I go to Gitter in Safari, the high perf GPU is not required. Neither is it required in Chrome.

**Comment by tscholak** [comment]
Curious. I restarted the Gitter app, and I can't reproduce what I saw just before. Now it doesn't require the high perf GPU.

**Comment by MadLittleMods** [comment]
If you can nail down reproduction, please explain.

[Upgrading to the latest NW.js](https://github.com/gitterHQ/desktop/pull/169) might also help the situation. I am not finding much info about "Requires High Perf GPU" especially in terms of NW.js or Electron.

**Comment by djspiewak** [comment]
I can confirm that I've seen this with the latest published builds.  Reproducing appears to be tricky.  I initially reproduced it by starting the application, confirming that it *wasn't* using the discrete GPU, then opening the *Notifications* configuration panel and closing it again.  This flipped the application to require the discrete GPU.  However, running these exact steps a second time failed to reproduce.

**Comment by djspiewak** [comment]
@MadLittleMods This is now (as of today's Sierra 10.12.3 update) 100% reproducible.  Opening Gitter simply requires the high performance GPU, every time.  Sometimes it takes a few seconds for the system to realize this as Gitter initializes, but it always figures it out pretty quickly.  Putting the app in full screen mode seems to force it a little faster, but we're talking about a few seconds either way.

**Comment by firedev** [comment]
Why was this closed? This is still a problem.

**Comment by djspiewak** [comment]
@firedev I'm assuming it's because @MadLittleMods wasn't able to reproduce the issue when it was closed.  In fairness, it *was* hard to reproduce deterministically back then.  It's trivial to reproduce now though (just open Gitter.app), so IMO this issue really should be reopened.

**Comment by MadLittleMods** [comment]
@firedev @djspiewak Things have continued on in https://github.com/gitterHQ/desktop/issues/183
