### ISSUE TITLE
Can't load rooms with non-latin characters in the URL

### ISSUE THREAD

**Issue by yesthatguy** [gitterHQ/desktop#181]
I created two communities: https://gitter.im/salomaki and https://gitter.im/salomäki

Both load fine in the web client, but only the first works in the desktop client. The second gives an error hinting at GitHub auth problems, but these communities are not connected to github. It seems like the real error has to do with the "ä" in the URL.

<img width="1053" alt="screen shot 2017-01-04 at 4 15 28 pm" src="https://cloud.githubusercontent.com/assets/10944164/21659507/10e464e8-d299-11e6-8e72-cf602af5ca3a.png">

This behavior happens with other communities as well:
https://gitter.im/AlexTrapp/FreeCodeCampEspañol
https://gitter.im/pasosdeJesus/Traducci%C3%B3nEspa%C3%B1olFreeCodeCamp

**Comment by MadLittleMods** [comment]
This seems to happen with the Safari-backed desktop app we currently push on macOS.

You can use the NW.js version of the app which doesn't appear to have tihs issue, https://update.gitter.im/osx/Gitter-3.1.0.dmg

**Comment by yesthatguy** [comment]
Thanks @MadLittleMods 

When I download that other version and copy it to my Applications folder, I get the error:
"Gitter" is damaged and can't be opened. You should move it to the Trash.

I tried removing ~/Library/Application Support/Gitter but that didn't help.

When I try to open the app directly from the disk image, I get:
"Gitter" can't be opened because it is from an unidentified developer.
Even if I click "Open Anyway" in the Security preferences, it doesn't open...I just get that same error again.

Let me know if you'd rather have me open a different issue for this or if there's another way to go about it.
