### ISSUE TITLE
Notification Settings in OS X

### ISSUE THREAD

**Issue by mwmg** [gitterHQ/desktop#189]
When opening the notification settings, there are no buttons for applying changes or for configuring defaults. There is therefore no way to change the notification settings in the OS X desktop app.

I'm running Gitter v1.177 under OS X 10.10.5.

**Comment by MadLittleMods** [comment]
> I am guessing this is the safari-based macOS app on an older version of OS X. This is a bug with any modal.
>
> You can download the NW.js version of the app that shouldn't have the issue, https://update.gitter.im/osx/Gitter-3.1.0.dmg
>
> https://github.com/gitterHQ/gitter/issues/1602#issuecomment-277104073


See

 - https://github.com/gitterHQ/gitter/issues/1602
 - https://github.com/gitterHQ/gitter/issues/1574

**Comment by mwmg** [comment]
Thanks, it works now! Is there a way to automatically update to that version though? When I checked for updates, it would say that it was up to date.

**Comment by MadLittleMods** [comment]
@mwmg It's a completely separate app and are not pushing it out for macOS currently because we want to improve auto-update. It is shipped for Windows and linux though.
