### ISSUE TITLE
Tray Icon — Linux

### ISSUE THREAD

**Issue by waltfy** [gitterHQ/desktop#19]
On Linux we have a white line at the bottom of the icon, as seen below:
![screen shot 2015-02-02 at 16 36 51](https://cloud.githubusercontent.com/assets/1257595/6004305/bb4b3322-aaf9-11e4-8a35-ab68f9b5d03f.png)

**Comment by mydigitalself** [comment]
I'll update this to make a Linuxy one in off-white. The Mac icon actually has this line as well, you just don't really notice it as it sits on a white-based bar.
