### ISSUE TITLE
VirusTotal positive detection on Windows app

### ISSUE THREAD

**Issue by phades69** [gitterHQ/desktop#194]
The official Gitter app for Windows shows positive in virus scans,
https://www.virustotal.com/en/file/897c7a0e2b45f57c2e2651b7cca795f681407378d5974d3694dfd986070fca7b/analysis/1489685928/

Antivirus Result 
 - Invincea virus.win32.sality.at 20170203
    - https://www.microsoft.com/security/portal/threat/Encyclopedia/entry.aspx?Name=Virus%3AWin32%2FSality.AT
 - Jiangmin Downloader.Generic.fni 20170316
    - https://www.microsoft.com/security/portal/threat/encyclopedia/Entry.aspx?Name=Trojan:Win32/WisdomEyes.A

**Comment by MadLittleMods** [comment]
😕 Re-building from source, gives the same report on Virustotal with two detections. If you build from source without signing, do you still get the same detections?

Malwarebytes and Windows Defender don't show any threats when I scan the built exe, the installation directory, or my system as a whole. My ISP hasn't detected any bot traffic on my network.

`virus.win32.sality.at`: Looking at the technical info on https://www.microsoft.com/security/portal/threat/Encyclopedia/entry.aspx?Name=Virus%3AWin32%2FSality.AT

 - I don't see `%SystemRoot%\system32\drivers\amsint32.sys` on my PC
 - I can still edit my registry
 - I don't see the registry entries it tries to set

---

I am leaning to this being a false-positive. Perhaps it doesn't like our auto-update process, https://github.com/edjafarov/node-webkit-updater
