### ISSUE TITLE
open source it

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/desktop#2]
Prerequisites
------------------

- [ ] open source all dependencies
- [ ] remove all private tokens from git
- [ ] publish packages to npm

**Comment by mydigitalself** [comment]
We should probably include the Windows InnoSetup sources somehow in case anyone fancies mucking in to make the installer better.

**Comment by trevorah** [comment]
[Appveyor](http://www.appveyor.com/) and [chocolatey](https://chocolatey.org/packages/InnoSetup) might be able to do it.

**Comment by thequbit** [comment]
:+1:

**Comment by webknjaz** [comment]
- [ ] publish license

**Comment by thequbit** [comment]
:+1:

**Comment by trevorah** [comment]
:tada: 

@webknjaz the license is MIT.
