### ISSUE TITLE
Ubuntu 14.04 - error while loading shared libraries: libudev.so.0

### ISSUE THREAD

**Issue by dagar** [gitterHQ/desktop#21]
% gitter 
gitter: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

Ubuntu 14.04 64
gitter 2.2.2 amd64

nw.js solution (can be fixed in the package)
https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0

**Comment by thecatwasnot** [comment]
I'm having the same issue, also Ubuntu 14.04 64 however:
```bash
$ gitter
gitter: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
$ ls -l libudev.so.0 
lrwxrwxrwx 1 root root 34 Feb  7 07:37 libudev.so.0 -> /lib/x86_64-linux-gnu/libudev.so.1
$ ls -l /lib/x86_64-linux-gnu/libudev.so.1
lrwxrwxrwx 1 root root 16 Nov 18 09:39 /lib/x86_64-linux-gnu/libudev.so.1 -> libudev.so.1.3.5
```
Linking, etc all seems to be in order.

**Comment by gserrg** [comment]
Hi, I helped symlink ln -s /lib/x86_64-linux-gnu/libudev.so.1 /usr/lib/libudev.so.0
Ubuntu 14.10 x64
gitter 2.2.2 amd64

**Comment by thecatwasnot** [comment]
@gserrg That link got me running, thanks :)  (It looks like gitter just needs to look in the proper place for the lib)

**Comment by malditogeek** [comment]
Just uploaded a new version (2.2.3) that fixes this issue :+1:

**Comment by malditogeek** [comment]
Links on the README https://github.com/gitterHQ/desktop. Also added some instructions to enable the systray on Ubuntu14, looks like Unity disabled them on the latest release https://github.com/gitterHQ/desktop#tray-icon-on-ubuntu (more: ubuntuforums.org/showthread.php?t=2217458)

**Comment by jc00ke** [comment]
Thanks @malditogeek!

**Comment by walkman4321** [comment]
Hi
I want to use static library libudev.a instead of libudev.so.I want to build  my project as static.I can't find  it in  my ubuntu 14.04 system but  libudev.so is already have in my system.Please help where can i get libudev.a file
