### ISSUE TITLE
Add a capability to use a proxy

### ISSUE THREAD

**Issue by punker76** [gitterHQ/desktop#26]
First...thx for the win app (and all other gitter stuff), but I'm often at work with a proxy, so I can't use it and must use the web.

It would be nice to configure a proxy
or
the app uses the `http_proxy` or `https_proxy` environment variables
or
something else :-D

@punker76

**Comment by MadLittleMods** [comment]
Closed in favor of https://github.com/gitterHQ/desktop/issues/49
