### ISSUE TITLE
Adding GitHub integration not working correctly

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/desktop#3]
When adding a GitHub integration, oAuth with GitHub happens in external browser and never returns correctly.

**Comment by waltfy** [comment]
Is this blocking the first release for the `30/01/2015`?

**Comment by waltfy** [comment]
As suggested by @trevorah we can read the parent `iframe`'s `nwdisable` attribute, if the attribute is present open integrations on the default browser.
