### ISSUE TITLE
Check for transport

### ISSUE THREAD

**Issue by waltfy** [gitterHQ/desktop#31]
add `if (!this._transport) return;` to `javascript/dispatcher.js:108:_sendEnvelope()` or cherry pick https://github.com/faye/faye/commit/4dad37cf031eede2c698ded757888c06db39d885 into our branch.

**Comment by trevorah** [comment]
@suprememoocow do you know anything about this?

**Comment by waltfy** [comment]
This should be fixed Andy.

**Comment by trevorah** [comment]
Sweet!
