### ISSUE TITLE
Windows: Autostart cannot be disabled inside the app, should be optional

### ISSUE THREAD

**Issue by quassy** [gitterHQ/desktop#39]
Firstly, Gitter should actually ask if it should be added to Autostart. 

Secondly, it should be possible to disable Autostart from inside the app (main menu).

**Comment by trevorah** [comment]
Hmm, I thought that it did. Which os is this on?

**Comment by troupe-admin** [comment]
Nope, it's not an option in the app, the Windows installer asks, I think
it's on the last page.

**Comment by Peilun0912** [comment]
I have same issue. I told the installer not to start app on Windows startup, but the app still starts every time.

My OS is Windows 8.1 64-bit

**Comment by MadLittleMods** [comment]
On Windows 8.1, you can easily disable any app on start-up by going to the Task Manager -> Startup tab -> Disable any entry

**Comment by MadLittleMods** [comment]
Closing as this has been possible for a while now.

![](http://i.imgur.com/vEMeLLG.png)

**Comment by MichielHuijse** [comment]
I think this is a usability issue, it was not clear for me that this second 'gitter' text is a button.

**Comment by MadLittleMods** [comment]
@MichielHuijse We could make it more obvious by adding some more of the familiar menu items but it is a fairly standard pattern.

![](http://i.imgur.com/n6mwtrM.png)

PR welcome
