### ISSUE TITLE
Windows app - increase the font size of the talks

### ISSUE THREAD

**Issue by alxmcr** [gitterHQ/desktop#41]
#### Hello everyone. 

Please. Help in using the official application for Windows Gitter , **How can I increase the font size of the talks ?** I think the default size is very small. 

Successes , I would appreciate help me solve this detail.

**Comment by suprememoocow** [comment]
It should be fairly easy to add Zoom-In and Zoom-Out menus (and corresponding hotkeys) using https://github.com/nwjs/nw.js/wiki/Window#windowzoomlevel

**Comment by trevorah** [comment]
Im going to merge this with https://github.com/gitterHQ/desktop/issues/28 as @thequbit has already raised this.
