### ISSUE TITLE
Clicking github username navigates inside of app

### ISSUE THREAD

**Issue by akoeplinger** [gitterHQ/desktop#50]
Steps to reproduce:
1. Hover over the avatar of a user in the chat history
2. Click on his/her github username

Result:
It navigates to github **inside** of the gitter app. The usual gitter UI is hidden at this point (though I can navigate back by pressing the backspace key).

Expected:
It should open a separate browser window.

**Comment by mydigitalself** [comment]
Thanks for the great spot and bug report. Oddly this has never been reported before and the issue actually exists in the Gitter webapp rather than the desktop app. I've put in a fix that should get rolled out on Tuesday alongside some other changes.
