### ISSUE TITLE
idea: treat desktop app like a 3rd party app

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/desktop#55]
So obfuscation of our production oAuth key pair is a necessary pain with our current setup. Our keys are special as the user doenst need to approve the app. OAuth key leaks are inevitable and annoying (see [twitters own oAuth leak](http://thenextweb.com/twitter/2013/03/07/twitters-api-keys-and-secrets-surface-for-its-official-apps-what-should-we-do-with-them/)). Obfuscation is a tricky and unreliable part of the build for us and (most problematic of all) cannot be performed by someone outside of gitter, so its almost impossible for them to contribute to the build.

What if we had a key that was just the same as any third party key?

There would be one more approval step for the user when logging in, but thats it. The key pair is no longer special, and so we dont have to be as protective. Our installers/apps are signed by us, so we still have control over what is the Official Gitter Desktop App<sup>tm</sup>.

Thoughts?

/cc @malditogeek @suprememoocow @mydigitalself

**Comment by malditogeek** [comment]
:+1: for simplicity

Also, having the confirmation step is probably a good thing.

**Comment by trevorah** [comment]
Done in master.
