### ISSUE TITLE
Linux desktop app autostart

### ISSUE THREAD

**Issue by dagar** [gitterHQ/desktop#56]
Please add autostart for Ubuntu.

**Comment by mydigitalself** [comment]
How about a pull request... ? :)

**Comment by dagar** [comment]
Fair enough. It's easy to throw an entry in ~/.config/autostart, but then it would autostart by default. Could the gitter app have an option to add/remove the autostart file?

**Comment by mydigitalself** [comment]
Well that's what I'm saying, it wouldn't be a far cry to add this capability by pull request. We can look to do it ourselves in a few weeks. In theory it wouldn't be too difficult to add this, best place to start would be nwapp/components/menu-items.js
