### ISSUE TITLE
Windows taskbar notifcation

### ISSUE THREAD

**Issue by JoeHegarty** [gitterHQ/desktop#57]
It would be nice if the Windows client would flash/highlight the Gitter icon on the taskbar.
I think that paradigm for notifications is more usual for windows users (Skype etc use this method).

**Comment by MadLittleMods** [comment]
Even though this is on the desktop repo where it belongs. I am going to close this in favor of https://github.com/gitterHQ/gitter/issues/1043 because of the activity.
