### ISSUE TITLE
Gitter windows desktop app opens as node-webkit in title and background as ascii art

### ISSUE THREAD

**Issue by eeevans** [gitterHQ/desktop#59]
![image](https://cloud.githubusercontent.com/assets/272717/7300665/21d9b126-e9a3-11e4-9902-5c635edb75f7.png)

Used GitterSetup-2.3.2.exe.  This is on a new Dell Tower 7810 with x64 Win 7 pro.
Installed on a laptop running Win 7 Ultimate x64 with no issue

**Comment by mydigitalself** [comment]
Thanks for filing. Will get @trevorah or @malditogeek to investigate with you.

**Comment by VictorBlomberg** [comment]
I have the same issue on Windows 7 Pro, with both 2.3.1 and 2.3.2 (haven't tested any other version). Reinstall didn't help.

**Comment by mydigitalself** [comment]
@eeevans you installed it on a different version of Windows 7 without any issues?

**Comment by eeevans** [comment]
Yes, I installed it on a laptop with Win 7 Ultimate without issue.  I also tried reinstall on Win 7 pro and it didn't help.

**Comment by thomaslevesque** [comment]
I have exactly the same issue on Windows 8.1 x64 (Update 1)

**Comment by Moncader** [comment]
I have the same issue on Linux 64 bit.

**Comment by wholroyd** [comment]
I can reproduce this as well. Windows 7 64bit, all patches and service packs applied. Interestingly enough, other platforms are having the same issue - https://github.com/phonegap/phonegap-app-desktop/issues/362

**Comment by MatthewSmythe** [comment]
I am seeing the same issue here. Tried 0.1.2, 0.1.4, 0.1.6. I'm running Windows 8.1 Enterprise 64 bit.

**Comment by DevProLog** [comment]
I have the same issue!

**Comment by hermwong** [comment]
I'm getting a lot of users reporting this issue on Windows 7 64-bit, Windows 8.1 64-bit and Windows 10 64-bit.

Related issues: https://github.com/phonegap/phonegap-app-desktop/issues/362 and https://github.com/phonegap/phonegap-app-desktop/issues/372

**Comment by tomhundley** [comment]
I had the same issue.  I ran it as administrator and it worked after that (not sure what possessed me to do that).  I can run it w/o admin rights now.

**Comment by moloko** [comment]
Same issue here (Win7 64-bit), although only sporadically. Some days its absolutely fine but then there are days when it will only do this no matter how many times I quit and relaunch.

Running it as administrator didn't make any difference.

**Comment by Hiroaki-Komori** [comment]
I launced it doubly, then it runs in one side. Of course the other side is node-webkit.

**Comment by eeevans** [comment]
Anything else I can do to help troubleshoot/debug?

**Comment by MadLittleMods** [comment]
@eeevans You could try following [these steps](https://github.com/gitterHQ/desktop/issues/69#issuecomment-126656798) I wrote for little bit of a different issue but I am curious to see if they work for this: https://github.com/gitterHQ/desktop/issues/69#issuecomment-126656798

**Comment by trevorah** [comment]
Hey windows peeps, we're pretty sure we've found the culprit (v8-snapshots). Can you please try out this alpha and see if this still happens: http://we.tl/W0hPS1KXgj

**Comment by moloko** [comment]
@trevorah working so far, but the previous version would sometimes work and sometimes not so I'll need to see how it behaves over a few days' usage

**Comment by trevorah** [comment]
thanks @moloko!

**Comment by eeevans** [comment]
Did not work for me...same outcome.

**Comment by trevorah** [comment]
@eeevans any chance you could install sawbuck, enable log capture and try and run gitter? There are some instructions here: https://gist.github.com/trevorah/bfeb4ad69e4633dc76c5

**Comment by eeevans** [comment]
ERROR	26124	1984	12:30:23-011	d:\slave\win32_master\node-webkit\src\content\browser\compositor\gpu_process_transport_factory.cc	418	Failed to establish GPU channel.

**Comment by trevorah** [comment]
I've seen that before on a working app. Looks like a red herring.

**Comment by eeevans** [comment]
That's all I got...I ran it as Administrator.

**Comment by eeevans** [comment]
I turned on verbose
VERBOSE	25228	7752	13:10:21-147	d:\slave\win32_master\node-webkit\src\content\nw\src\nw_package.cc	230	Package startup URL: nw:blank
VERBOSE	25228	7752	13:10:21-148	d:\slave\win32_master\node-webkit\src\content\nw\src\nw_shell.cc	188	enable nodejs from manifest: 1
VERBOSE	25228	7752	13:10:21-158	d:\slave\win32_master\node-webkit\src\content\nw\src\browser\native_window_aura.cc	373	NativeWindowAura::Show(); initial_focus = 1
ERROR	25228	7752	13:10:21-169	d:\slave\win32_master\node-webkit\src\content\browser\compositor\gpu_process_transport_factory.cc	418	Failed to establish GPU channel.
VERBOSE	25228	7752	13:10:21-173	d:\slave\win32_master\node-webkit\src\content\browser\media\webrtc_internals.cc	52	Could not get the download directory.
VERBOSE	15148	25496	13:10:21-182	d:\slave\win32_master\node-webkit\src\content\child\child_thread.cc	242	Mojo is disabled on child
VERBOSE	25228	24252	13:10:21-340	d:\slave\win32_master\node-webkit\src\content\browser\loader\resource_loader.cc	316	OnResponseStarted: nw:blank
VERBOSE	25228	24252	13:10:21-340	d:\slave\win32_master\node-webkit\src\content\browser\loader\resource_loader.cc	356	OnReadCompleted: "nw:blank" bytes_read = 1082
VERBOSE	25228	24252	13:10:21-340	d:\slave\win32_master\node-webkit\src\content\browser\loader\resource_loader.cc	356	OnReadCompleted: "nw:blank" bytes_read = 0
VERBOSE	25228	24252	13:10:21-340	d:\slave\win32_master\node-webkit\src\content\browser\loader\resource_loader.cc	645	ResponseCompleted: nw:blank
VERBOSE	15148	23148	13:10:21-340	d:\slave\win32_master\node-webkit\src\ipc\ipc_sync_channel.cc	316	Received error reply
VERBOSE	15148	23148	13:10:21-342	d:\slave\win32_master\node-webkit\src\ipc\ipc_sync_channel.cc	316	Received error reply
VERBOSE	15148	23148	13:10:21-342	d:\slave\win32_master\node-webkit\src\ipc\ipc_sync_channel.cc	316	Received error reply
VERBOSE	15148	23148	13:10:21-342	d:\slave\win32_master\node-webkit\src\ipc\ipc_sync_channel.cc	316	Received error reply
VERBOSE	15148	25496	13:10:21-346	d:\slave\win32_master\node-webkit\src\content\nw\src\renderer\shell_content_renderer_client.cc	298	WillSetSecurityToken: nw:blank
VERBOSE	15148	25496	13:10:21-346	d:\slave\win32_master\node-webkit\src\content\nw\src\renderer\shell_content_renderer_client.cc	300	GOOD FOR NODE
VERBOSE	15148	25496	13:10:21-347	d:\slave\win32_master\node-webkit\src\content\nw\src\renderer\shell_content_renderer_client.cc	298	WillSetSecurityToken: nw:blank
VERBOSE	15148	25496	13:10:21-347	d:\slave\win32_master\node-webkit\src\content\nw\src\renderer\shell_content_renderer_client.cc	300	GOOD FOR NODE
VERBOSE	15148	25496	13:10:21-348	d:\slave\win32_master\node-webkit\src\content\nw\src\renderer\shell_content_renderer_client.cc	233	DidCreateScriptContext: nw:blank
VERBOSE	15148	23148	13:10:32-153	d:\slave\win32_master\node-webkit\src\ipc\ipc_sync_channel.cc	386	Canceling pending sends

**Comment by trevorah** [comment]
Thanks @eeevans, let me take a look...

**Comment by trevorah** [comment]
The first line is the problem:
```
VERBOSE 25228 7752 13:10:21-147 d:\slave\win32_master\node-webkit\src\content\nw\src\nw_package.cc 230 Package startup URL: nw:blank
```
The startup url should be `app://gitter/index.html`. Node webkit reads this from the compressed package.json from launch. I'll take a deeper look.

**Comment by trevorah** [comment]
This could be a windows path length thing :sob: We have some node_modules that are reaching 200 chars in length. I'll try building a version with npm 3.x.

**Comment by MadLittleMods** [comment]
@trevorah The only time I ever have a problem with path name length is when trying to delete `node_modules` from the file explorer. But I can do it from the command line easily with something like [`rimraf`](https://www.npmjs.com/package/rimraf).

Although I cam very curious whether this fixes it.

**Comment by trevorah** [comment]
@eeevans new build with shorter paths: http://we.tl/UBo4Fpynej

Let me know if it starts or not.

**Comment by eeevans** [comment]
Yes, that fixed it!!!

**Comment by MadLittleMods** [comment]
@trevorah 

@johntom confirmed that Gitter-2.3.3-alpha.2 fixed the issue!

**Comment by moloko** [comment]
it's been working fine for me so far too

**Comment by trevorah** [comment]
Good stuff. I probably wont be getting an official release (with a proper installer) out until next week (we have a bank holiday weekend here in the uk).

For the curious:

1. the desktop client has node dependencies that npm 2.x (current stable release) installs in a nested manner e.g `node-webkit-updater/node_modules/tar.gz/node_modules/fstream/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/test/balanced.js`
2. node webkit unpacks these into a temp folder when starting up
3. node webkit then tries to read these files, but the paths can potentially exceed the infamous windows 256 char limit. Whether or not the path is too long varies from machine to machine based on the length of the path to the temp folder.
4. node webkit doesnt raise an error and just falls back to its default start state (the ascii art).

The solution was to install the node dependencies with npm 3.x, which flattens dependencies as much as possible.

**Comment by trevorah** [comment]
The 2.3.3 release is live, grab the new installer here: https://update.gitter.im/win/latest

Old (installed) clients should be able to autoupdate. I'm not sure what the standalone alpha builds will do, so you should probably just use the new installer.

**Comment by eeevans** [comment]
Installed client autoupdated and is working great! Thanks

**Comment by trevorah** [comment]
no problem @eeevans, thanks for reporting and being a helpful test subject!
