### ISSUE TITLE
[OS X] UI bug when trying to create a new room

### ISSUE THREAD

**Issue by zankevich** [gitterHQ/desktop#60]
1. Open gitter mac os x app
2. Click "Create a room" button
3. Click on any room type

When you clicking on radio buttons some UI bugs appeared on left top of app window.

OSX 10.10.3

**Comment by mydigitalself** [comment]
Hi there, could you please attach a screenshot, we can't reproduce this.

**Comment by zankevich** [comment]
[Video (Dropbox ~6 mb)](https://www.dropbox.com/s/35kv33jnjpj9ew4/bug.mov?dl=0)

**Comment by trevorah** [comment]
Thats so weird. I wonder why the web view would render like that?
