### ISSUE TITLE
Can't hide a group that is no longer available

### ISSUE THREAD

**Issue by vrunoa** [gitterHQ/desktop#66]
Hey guys, i'm using gitter(v1.162) desktop for mac and I cannot hide or leave a group chat that is no longer available. 
Checking the developers tools console, I got this error;
```
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (54d6b3e715522ed4b3dbbaf0, line 0) https://api.gitter.im/v1/user/54df786215522ed4b3dc041d/rooms/54d6b3e715522ed4b3dbbaf0
{"error":"An unknown error occurred"}
```
The group is ```iojs/iojs-es```.

**Comment by mydigitalself** [comment]
Should be fixed for you now.

**Comment by vrunoa** [comment]
:+1:
