### ISSUE TITLE
Stop Gitter from opening on start-up

### ISSUE THREAD

**Issue by TransisterSistor** [gitterHQ/desktop#70]
I don't want this to open every time I turn on my computer. Must I cancel in order to have this not happen?

**Comment by MadLittleMods** [comment]
Hey @TransisterSistor, what platform are you on?

On Windows 8.1, you can go into the Task Manager -> Startup tab. Then find the Gitter entry and disable.

![](http://i.imgur.com/KjCyPKF.png)

**Comment by TransisterSistor** [comment]
Bummer. Not Windows 8.1
Windows 7?

**Comment by MadLittleMods** [comment]
@TransisterSistor Open `Run`, type in `msconfig`. Go to the `Startup` tab and disable the Gitter Entry.

**Comment by TransisterSistor** [comment]
thank you MadLittleMods!
