### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by rfikki** [gitterHQ/desktop#78]
Cannot seem to uninstall in windows 10. Tried the normal uninstall but the program remains running. Any a help appreciated

**Comment by MadLittleMods** [comment]
Just exit the program and remove this folder if it still exists: `C:\Users\yourusernamehere\AppData\Local\Programs\Gitter`

**Comment by rfikki** [comment]
Thanks for the response. Will give it a try. I am going back to the browser based version. The desktop version was a bit to invasive for my needs.

**Comment by MadLittleMods** [comment]
I assume this worked from the lack of response.

**Comment by MadLittleMods** [comment]
You can run the uninstaller located here: "C:\Users\yourusernamehere\AppData\Local\Programs\GitterUninstaller\unins000.exe"

**Comment by rfikki** [comment]
Yes, I was able to solve this with your assistance. Thanks.

**Comment by craftworkgames** [comment]
I ran into this issue also. Running the uninstaller from Programs and Features don't actually remove the app. It does seem to remove the uninstaller however :)

Anyway, deleting the folder in `AppData\Local\Programs\Gitter\` does work as a workaround, but it's still not completely removed unfortunately.

As shown in this screenshot, the system still tries to run the app on Startup

![image](https://cloud.githubusercontent.com/assets/3201643/18775818/ee111ffc-81a7-11e6-8434-b8acce274295.png)

I think the solution is to delete it from the registry

`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\Gitter`

**Comment by neurogirl47** [comment]
@craftworkgames How do you mean "delete it from the registry"?

**Comment by neurogirl47** [comment]
@craftworkgames Never mind. I figured it out.
