### ISSUE TITLE
Linux/Ubuntu PowerPC Build?

### ISSUE THREAD

**Issue by PFCKrutonium** [gitterHQ/desktop#83]
I have an older PowerBook G4 that I use for development, would it be possible to get a proper app for this?

**Comment by MadLittleMods** [comment]
Does the normal linux app work on your platform? http://gitter.im/apps

We probably won't dedicate dev time to an older platform if it requires special attention. But feel free to send a PR as the desktop app is open source.

**Comment by PFCKrutonium** [comment]
PowerPC is a Big Endian RISC CPU similar to ARM that was used in Apple Computers up until they switched to using Intel CPU's.

**Comment by PFCKrutonium** [comment]
Would you guys be willing to do an official PowerPC Build if I can get it working?

**Comment by mydigitalself** [comment]
I very much doubt we would officially support it @PFCKrutonium but if you can get it working for yourself, go for it.

**Comment by PFCKrutonium** [comment]
Turns out that while it is available, npm is hilariously broken.
