### ISSUE TITLE
Copy links from chat (context menu)

### ISSUE THREAD

**Issue by cbj4074** [gitterHQ/desktop#87]
Currently, right-clicking seems to be disabled in the Desktop Client. As such, it is impossible to copy links from the chat and, for example, paste them into a browser.

Oftentimes, I do not want a link within the chat to open my default browser when clicked. Rather, I would prefer to copy/paste the link into a browser of my choosing.

This is not a problem in the Web Client, because right-clicking is not disabled there. If right-clicking is not an option in the Desktop Client, then some kind of hover-based button might work.

Maybe there are even better ways to implement this...

**Comment by mydigitalself** [comment]
Ctrl/CMD+C ?

**Comment by MadLittleMods** [comment]
@mydigitalself There can be [inline links](https://gitter.im/) and while we do copy as markdown, being able to have the normal right click functionality would be really nice to get just the link and give something familiar.

I haven't tested yet right-click is actually disabled in the desktop client though.

**Comment by cbj4074** [comment]
Thanks, you beat me to it, @MadLittleMods :smiley_cat:

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/desktop/issues/12
