### ISSUE TITLE
User attribution when quoting a message.

### ISSUE THREAD

**Issue by edgarshurtado** [gitterHQ/desktop#90]
Hi, I'm using regularly Gitter with my FreeCodeCamp fellows. When I try to answer a past comment I usually do a quotation. Unfortunately, Gitter just copy the text i'm quoting, but it would be great if the software added the user I'm quoting too. Something like this:

> Message from @userrandom
>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec orci nec neque.

**Comment by MadLittleMods** [comment]
Please move this to the main Gitter repo. This is not desktop specific: https://github.com/gitterHQ/gitter

**Comment by MadLittleMods** [comment]
Note: This issue was moved here https://github.com/gitterHQ/gitter/issues/1048
