### ISSUE TITLE
Mac OS minimize shortcut should me command-M

### ISSUE THREAD

**Issue by GregOriol** [gitterHQ/desktop#91]
Currently, on Mac OS, the shortcut to minimize the window into the Dock is... 5 keys (ctrl-alt-shift-command-M) and doesn't match the "standard" of all other apps: it should be command-M
<img width="499" alt="capture d ecran 2016-01-08 a 08 46 51" src="https://cloud.githubusercontent.com/assets/3975044/12193005/76d0f3fc-b5e4-11e5-8210-5713f069a1fd.png">

**Comment by michaelsbradleyjr** [comment]
Yes, please change the binding to command-M.  I would be happy to submit a pull request, but I couldn't find where in the source code the binding is getting set or where it can be overridden.

**Comment by MadLittleMods** [comment]
@michaelsbradleyjr It is probably part of `node-webkit`/`nw.js` itself. We will be upgrading `nw.js` soon and perhaps it is exposed better on the newer version.

**Comment by jason0x43** [comment]
I'm using Gitter 1.177 and it's still using the odd minimize shortcut. Has the code that was supposed to fix this been released yet? The versioning system seems a bit confusing (this repo says the client is at version 3+, but the latest download for Mac OS is 1.177?).

**Comment by MadLittleMods** [comment]
@jason0x43 The 1.x versioning on macOS is the Safari-based version which we still distribute.

You can download the NW.js which we distribute for all platforms (and works on macOS), https://update.gitter.im/osx/Gitter-3.1.0.dmg

**Comment by jason0x43** [comment]
Ah, I wondered if that might be the case, but I was unable to find a link anywhere to the NW.js version. Thanks!
