### ISSUE TITLE
Digital signature expired on Gitter.exe

### ISSUE THREAD

**Issue by warden** [gitterHQ/desktop#93]
There is a digital signature on `Gitter.exe` from Troupe Technology Limited but it expired on December 18th 2015.

Comodo Internet Security is reporting that Gitter has not been digitally signed and is requesting unlimited access to computer(why?) and suggests running it in isolated sandbox. It does run fine isolated.

**Comment by MadLittleMods** [comment]
![](http://i.imgur.com/ZSVxTdH.png)
