### ISSUE TITLE
awesome wm + naughty notification library shows gitter icon too large

### ISSUE THREAD

**Issue by bernieke** [gitterHQ/desktop#94]
The default icon sent to the notification system is too large, causing the notification to take up over a quarter of the available real estate on a full hd display.

Unlike fi. the gnome notification library, naughty doesn't automatically scale back the icon.

You can configure naughty to fix the icon at a certain size by adding the following to your awesome rc.lua
```
naughty.config.defaults.icon_size = 16
```

**Comment by MadLittleMods** [comment]
Thanks for creating the issue as a reference for others :grinning:

**Comment by aledeg** [comment]
I had the same issue with some Firefox notification. It's fixed now :)
